In [1]:
import pandas as pd
import json
from collections import Counter
from pathlib import Path


df_keybert = pd.read_csv("../dataset_comparative_2020_2026/comparative_files/keywords_keybert_meta.csv")
print(f"Документів: {len(df_keybert):,}")
df_keybert.head()

Документів: 8,427

,doc_id,length,rubric,outcome,num_stages,main_committee,card_id,reg_num,reg_date,keywords_keybert,num_keywords
0,12273_Порівняльна таблиця (04.12.2024),172,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45350,12273,2024-12-02,"[""бюджет україни"", ""україни 2023"", ""закон укра...",5.0
1,12272_Порівняльна таблиця (04.12.2024),376,Економічна політика,in_progress,4,Підласа Р. А. Комітет Верховної Ради України з...,45328,12272,2024-12-02,"[""бюджетний кодекс"", ""україни відомості"", ""зді...",5.0
2,12274_Порівняльна таблиця (03.12.2024),145,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45349,12274,2024-12-02,"[""бюджет україни"", ""україни 2023"", ""закон укра...",5.0
3,12275_Порівняльна таблиця (04.12.2024),476,Безпека і оборона,in_progress,4,Завітневич О. М. Комітет Верховної Ради Україн...,45341,12275,2024-12-02,"[""закону україни"", ""закон україни"", ""законами ...",5.0
4,12276_Порівняльна таблиця (04.12.2024),499,Економічна політика,in_progress,4,Гетманцев Д. О. Комітет Верховної Ради України...,45363,12276,2024-12-02,"[""особливостей оподаткування"", ""податку стаття...",5.0

In [2]:
from collections import defaultdict
import json

# Підрахунок document frequency для KeyBERT
doc_freq = defaultdict(int)
for kw_json in df_keybert["keywords_keybert"]:
    try:
        kw_list = json.loads(kw_json)
        unique_kw = set(
            kw.lower().strip()
            for kw in kw_list
        )
        for kw in unique_kw:
            doc_freq[kw] += 1
    except:
        pass

total_docs = len(df_keybert)
print(f"Всього документів: {total_docs}\n")
print(f"{'KW':<40} {'DF':>6} {'DF%':>7}")
print("-" * 60)
for kw, df_count in sorted(
    doc_freq.items(),
    key=lambda x: -x[1]
)[:50]:
    pct = df_count / total_docs * 100
    print(
        f"{kw:<40} "
        f"{df_count:>6} "
        f"{pct:>6.1f}%"
    )

Всього документів: 8427

KW                                           DF     DF%
------------------------------------------------------------
закону україни                             3801   45.1%
закон україни                              2508   29.8%
законів україни                            1775   21.1%
кодексу україни                            1526   18.1%
порівняльна таблиця                        1121   13.3%
міністрів україни                           981   11.6%
законом україни                             929   11.0%
бюджету україни                             707    8.4%
кодекс україни                              681    8.1%
україни підписувач                          628    7.5%
депутати україни                            616    7.3%
бюджет україни                              569    6.8%
україни стаття                              525    6.2%
норми проекту                               514    6.1%
актів україни                               504    6.0%
проекту закону                              484    5.7%
законодавства зміст                         479    5.7%
ради україни                                471    5.6%
депутат україни                             451    5.4%
конституції україни                         440    5.2%
республіки крим                             390    4.6%
законами україни                            347    4.1%
україни закон                               338    4.0%
україни реєстраційний                       315    3.7%
безпеки україни                             302    3.6%
законодавства україни                       301    3.6%
рада україни                                292    3.5%
адміністративні правопорушення              290    3.4%
деяких законодавчих                         283    3.4%
конституцією україни                        277    3.3%
податкового кодексу                         264    3.1%
законі україни                              247    2.9%
законодавством україни                      245    2.9%
законодавчих актів                          239    2.8%
акта законодавства                          215    2.6%
внесення змін                               201    2.4%
автономної республіки                       188    2.2%
бюджетного кодексу                          179    2.1%
кодексом україни                            171    2.0%
федерації донецькій                         154    1.8%
україни відомості                           152    1.8%
чинного законодавства                       148    1.8%
суддів україни                              148    1.8%
бюро україни                                144    1.7%
проєкту закону                              143    1.7%
визначення термінів                         143    1.7%
банку україни                               143    1.7%
міжнародних договорів                       142    1.7%
норми чинного                               138    1.6%
інвалідністю україні                        137    1.6%

In [3]:
all_kw_keybert = []
for kw_json in df_keybert["keywords_keybert"]:
    try:
        all_kw_keybert.extend([kw.lower().strip() for kw in json.loads(kw_json)])
    except:
        pass

counter_keybert = Counter(all_kw_keybert)
print(f"Унікальних KW: {len(counter_keybert):,}")
print(f"Всього KW: {len(all_kw_keybert):,}")
print(f"\nТоп-30:")
for kw, cnt in counter_keybert.most_common(30):
    print(f"  {cnt:>5}  {kw}")

Унікальних KW: 66,552
Всього KW: 176,349

Топ-30:
   3801  закону україни
   2508  закон україни
   1775  законів україни
   1526  кодексу україни
   1121  порівняльна таблиця
    981  міністрів україни
    929  законом україни
    707  бюджету україни
    681  кодекс україни
    628  україни підписувач
    616  депутати україни
    569  бюджет україни
    525  україни стаття
    514  норми проекту
    504  актів україни
    484  проекту закону
    479  законодавства зміст
    471  ради україни
    451  депутат україни
    440  конституції україни
    390  республіки крим
    347  законами україни
    338  україни закон
    315  україни реєстраційний
    302  безпеки україни
    301  законодавства україни
    292  рада україни
    290  адміністративні правопорушення
    283  деяких законодавчих
    277  конституцією україни

In [4]:
input_path = Path("../dataset_comparative_2020_2026/comparative_files/keywords_keybert_meta.csv")

df = pd.read_csv(input_path)

print(df.columns.tolist())
print("Документів:", len(df))
df.head()

['doc_id', 'length', 'rubric', 'outcome', 'num_stages', 'main_committee', 'card_id', 'reg_num', 'reg_date', 'keywords_keybert', 'num_keywords']
Документів: 8427

,doc_id,length,rubric,outcome,num_stages,main_committee,card_id,reg_num,reg_date,keywords_keybert,num_keywords
0,12273_Порівняльна таблиця (04.12.2024),172,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45350,12273,2024-12-02,"[""бюджет україни"", ""україни 2023"", ""закон укра...",5.0
1,12272_Порівняльна таблиця (04.12.2024),376,Економічна політика,in_progress,4,Підласа Р. А. Комітет Верховної Ради України з...,45328,12272,2024-12-02,"[""бюджетний кодекс"", ""україни відомості"", ""зді...",5.0
2,12274_Порівняльна таблиця (03.12.2024),145,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45349,12274,2024-12-02,"[""бюджет україни"", ""україни 2023"", ""закон укра...",5.0
3,12275_Порівняльна таблиця (04.12.2024),476,Безпека і оборона,in_progress,4,Завітневич О. М. Комітет Верховної Ради Україн...,45341,12275,2024-12-02,"[""закону україни"", ""закон україни"", ""законами ...",5.0
4,12276_Порівняльна таблиця (04.12.2024),499,Економічна політика,in_progress,4,Гетманцев Д. О. Комітет Верховної Ради України...,45363,12276,2024-12-02,"[""особливостей оподаткування"", ""податку стаття...",5.0

In [5]:
KEYWORD_COL = "keywords_keybert"

In [6]:
def parse_keywords(value):
    if pd.isna(value):
        return []

    if isinstance(value, list):
        return value

    try:
        return json.loads(value)
    except Exception:
        return []

In [7]:
import re

def normalize_kw(kw):
    kw = str(kw).lower().strip()
    kw = kw.replace("ґ", "г")
    kw = re.sub(r"[^\w\sіїє']", " ", kw, flags=re.UNICODE)
    kw = re.sub(r"\s+", " ", kw).strip()
    return kw

In [8]:
all_keywords = []

for value in df[KEYWORD_COL]:
    keywords = parse_keywords(value)

    for kw in keywords:
        kw_norm = normalize_kw(kw)

        if kw_norm:
            all_keywords.append(kw_norm)

kw_counter = Counter(all_keywords)
unique_keywords = sorted(kw_counter.keys())

print("Усього KW:", len(all_keywords))
print("Унікальних KW:", len(unique_keywords))

Усього KW: 176349
Унікальних KW: 66549

In [9]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

C:\Users\midzk\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 4652.34it/s]

In [10]:
embeddings = model.encode(
    unique_keywords,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

embeddings.shape

Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1040/1040 [04:50<00:00,  3.58it/s]

(66549, 384)

In [11]:
from sklearn.neighbors import NearestNeighbors
SIM_THRESHOLD = 0.82
TOP_K = 10

nn = NearestNeighbors(
    n_neighbors=min(TOP_K, len(unique_keywords)),
    metric="cosine",
    algorithm="brute"
)

nn.fit(embeddings)

distances, indices = nn.kneighbors(embeddings)

In [12]:
parent = list(range(len(unique_keywords)))

def find(x):
    while parent[x] != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x

def union(a, b):
    root_a = find(a)
    root_b = find(b)

    if root_a != root_b:
        parent[root_b] = root_a

In [13]:
for i in range(len(unique_keywords)):
    for dist, j in zip(distances[i], indices[i]):
        if i == j:
            continue

        similarity = 1 - dist

        if similarity >= SIM_THRESHOLD:
            union(i, j)

In [14]:
clusters = defaultdict(list)

for idx, kw in enumerate(unique_keywords):
    root = find(idx)
    clusters[root].append(kw)

multi_clusters = {
    label: kws
    for label, kws in clusters.items()
    if len(kws) > 1
}

print("Усього кластерів:", len(clusters))
print("Кластерів з 2+ фразами:", len(multi_clusters))

Усього кластерів: 3692
Кластерів з 2+ фразами: 598

In [15]:
shown = 0

for label, kws in multi_clusters.items():
    kws_sorted = sorted(kws, key=lambda x: kw_counter[x], reverse=True)

    print(f"\nCLUSTER {label} | size={len(kws_sorted)}")
    for kw in kws_sorted[:20]:
        print(f"  {kw:<45} DF={kw_counter[kw]}")

    shown += 1
    if shown >= 30:
        break

CLUSTER 66543 | size=60441
  закону україни                                DF=3801
  закон україни                                 DF=2508
  законів україни                               DF=1775
  кодексу україни                               DF=1526
  порівняльна таблиця                           DF=1121
  міністрів україни                             DF=981
  законом україни                               DF=929
  бюджету україни                               DF=707
  кодекс україни                                DF=681
  україни підписувач                            DF=628
  депутати україни                              DF=616
  бюджет україни                                DF=569
  україни стаття                                DF=525
  норми проекту                                 DF=514
  актів україни                                 DF=504
  проекту закону                                DF=484
  законодавства зміст                           DF=479
  ради україни                                  DF=471
  депутат україни                               DF=451
  конституції україни                           DF=440

CLUSTER 29393 | size=9
  кілограм або                                  DF=4
  кілограм тонна                                DF=4
  000 тонн                                      DF=1
  більше кг                                     DF=1
  кг маси                                       DF=1
  кілограмах масі                               DF=1
  кілограмах щорічно                            DF=1
  мг кг                                         DF=1
  перевищувати кілограмів                       DF=1

CLUSTER 6 | size=3
  01008                                         DF=1
  01008 www                                     DF=1
  київ 01008                                    DF=1

CLUSTER 46 | size=6
  арахамія враховано                            DF=4
  арахамія давид                                DF=2
  10 арахамія                                   DF=1
  арахамія                                      DF=1
  арахамія реєстр                               DF=1
  підписувач арахамія                           DF=1

CLUSTER 18945 | size=33
  1123 железняк                                 DF=4
  1173 железняк                                 DF=4
  1453 железняк                                 DF=4
  279 железняк                                  DF=2
  10 железняк                                   DF=1
  111 железняк                                  DF=1
  123 железняк                                  DF=1
  128 железняк                                  DF=1
  13 железняк                                   DF=1
  142 железняк                                  DF=1
  249 железняк                                  DF=1
  251 железняк                                  DF=1
  300 железняк                                  DF=1
  372 железняк                                  DF=1
  500 железняк                                  DF=1
  503 железняк                                  DF=1
  51 железняк                                   DF=1
  564 железняк                                  DF=1
  57 железняк                                   DF=1
  615 железняк                                  DF=1

CLUSTER 82 | size=3
  10 машин                                      DF=1
  10 транспортні                                DF=1
  11 транспортні                                DF=1

CLUSTER 11069 | size=7
  10 робочих                                    DF=7
  яти робочих                                   DF=7
  десяти робочих                                DF=3
  семи робочих                                  DF=2
  восьми працівників                            DF=1
  десять робочих                                DF=1
  сім робочих                                   DF=1

CLUSTER 121 | size=6
  формальдегід 6070                             DF=3
  10 формальдегід                               DF=1
  слова формальдегід                            DF=1
  формальдегід                                  DF=1
  формальдегід 6373                             DF=1
  формальдегід 6774                             DF=1

CLUSTER 130 | size=3
  1000 кубічних                                 DF=1
  1000 літрів                                   DF=1
  600 літрів                                    DF=1

CLUSTER 137 | size=2
  101 пасивне                                   DF=1
  13 пасивні                                    DF=1

CLUSTER 2978 | size=33
  281 салійчук                                  DF=4
  143 пузійчук                                  DF=3
  33 пузійчук                                   DF=2
  50 пузійчук                                   DF=2
  83 пузійчук                                   DF=2
  90 пузійчук                                   DF=2
  109 молоток                                   DF=1
  12 пузійчук                                   DF=1
  120 пузійчук                                  DF=1
  122 пузійчук                                  DF=1
  128 пузійчук                                  DF=1
  13 пузійчук                                   DF=1
  139 пузійчук                                  DF=1
  140 пузійчук                                  DF=1
  228 салійчук                                  DF=1
  290 молоток                                   DF=1
  32 пузійчук                                   DF=1
  37 пузійчук                                   DF=1
  38 пузійчук                                   DF=1
  393 пузійчук                                  DF=1

CLUSTER 180 | size=2
  11 воронов                                    DF=2
  92 воронов                                    DF=1

CLUSTER 65843 | size=29
  пестициди агрохімікати                        DF=7
  пестицидів агрохімікатів                      DF=7
  про пестициди                                 DF=7
  україни пестицидів                            DF=5
  випробувань пестицидів                        DF=4
  ефективності пестицидів                       DF=4
  реєстрація пестицидів                         DF=4
  до пестицидів                                 DF=3
  україні пестицидів                            DF=3
  пестицидами повинні                           DF=2
  пестицидів заборони                           DF=2
  пестицидів закон                              DF=2
  11 пестициди                                  DF=1
  забрудненні пестицидами                       DF=1
  отрути пестицидів                             DF=1
  перелік пестицидів                            DF=1
  пестицидів                                    DF=1
  пестицидів виключити                          DF=1
  пестицидів добрив                             DF=1
  пестицидів стаття                             DF=1

CLUSTER 252 | size=2
  113 невиконання                               DF=4
  137 невиконання                               DF=1

CLUSTER 285 | size=4
  791 відшкодування                             DF=3
  1173 відшкодування                            DF=2
  1206 відшкодування                            DF=2
  67 відшкодування                              DF=1

CLUSTER 295 | size=2
  119 вбивство                                  DF=1
  вбивство 14                                   DF=1

CLUSTER 3538 | size=4
  119 гарантії                                  DF=1
  57 гарантування                               DF=1
  65 гарантований                               DF=1
  82 гарантія                                   DF=1

CLUSTER 309 | size=4
  12 березня                                    DF=1
  березня року                                  DF=1
  неділю березня                                DF=1
  початок березня                               DF=1

CLUSTER 326 | size=2
  12 замовники                                  DF=1
  15 замовники                                  DF=1

CLUSTER 37811 | size=18
  ключові                                       DF=6
  визначити ключову                             DF=4
  наявність ключів                              DF=3
  застосуванням ключів                          DF=2
  12 ключові                                    DF=1
  26 ключовий                                   DF=1
  визначення ключових                           DF=1
  використання ключовий                         DF=1
  включати ключові                              DF=1
  ключ 83                                       DF=1
  ключа 17                                      DF=1
  ключовими показниками                         DF=1
  ключових                                      DF=1
  ключів та                                     DF=1
  перевірок ключових                            DF=1
  перелік ключових                              DF=1
  формування ключових                           DF=1
  щодо ключових                                 DF=1

CLUSTER 401 | size=2
  121 приватні                                  DF=1
  179 приватні                                  DF=1

CLUSTER 52767 | size=14
  солод 258                                     DF=11
  солей                                         DF=5
  солі                                          DF=2
  солі зазначається                             DF=2
  128 солод                                     DF=1
  калійна сіль                                  DF=1
  кухонної солі                                 DF=1
  редакції соління                              DF=1
  солей ефірів                                  DF=1
  солей норма                                   DF=1
  солод враховано                               DF=1
  солодового 76                                 DF=1
  солі норма                                    DF=1
  сіль або                                      DF=1

CLUSTER 479 | size=2
  129 будівлі                                   DF=1
  74 будівель                                   DF=1

CLUSTER 3665 | size=69
  58e2d9e7f900307b04000000235a2f00530f9200      DF=4
  2b6c7df9a3891da10400000006743d0087f6a301 дійсний DF=3
  58e2d9e7f900307b04000000440a3100ab198f00      DF=3
  2b6c7df9a3891da10400000006743d0087f6a301      DF=2
  2b6c7df9a3891da1040000003d95400041381202 дійсний DF=2
  2b6c7df9a3891da10400000045673d00939f5f02 дійсний DF=2
  2b6c7df9a3891da104000000ae164f006e408101      DF=2
  58e2d9e7f900307b04000000235a2f00530f9200 дійсний DF=2
  58e2d9e7f900307b040000002a672e002c9f8e00 дійсний DF=2
  58e2d9e7f900307b0400000053e22e0027179400      DF=2
  58e2d9e7f900307b0400000053e22e0027179400 дійсний DF=2
  58e2d9e7f900307b040000005d1531009e638f00 дійсний DF=2
  58e2d9e7f900307b040000008ee12e0039d48e00      DF=2
  58e2d9e7f900307b04000000d0512f00d41e8f00 дійсний DF=2
  58e2d9e7f900307b04000000e2183100b87a8f00 дійсний DF=2
  12a1c72050ec685404000000df510500a8390d00 дійсний DF=1
  20b4e4ed0d30998c0400000026532c0099b57800      DF=1
  20b4e4ed0d30998c04000000f3ca2900a53f6d00      DF=1
  2b6c7df9a3891da104000000018a3d002088cf01      DF=1
  2b6c7df9a3891da104000000084856003ddea401      DF=1

CLUSTER 5849 | size=10
  ароматизатори та                              DF=4
  13 ароматичні                                 DF=1
  ароматизатори значенні                        DF=1
  ароматизатори окремо                          DF=1
  ароматизаторів та                             DF=1
  закону ароматизатори                          DF=1
  значенні ароматизатори                        DF=1
  зокрема ароматизатори                         DF=1
  категорії ароматизатор                        DF=1
  наявність ароматизаторів                      DF=1

CLUSTER 527 | size=2
  13 користувачі                                DF=1
  16 користувачами                              DF=1

CLUSTER 556 | size=2
  13 постраждали                                DF=1
  постраждалим 16                               DF=1

CLUSTER 600 | size=2
  132 кальцев                                   DF=1
  143 кальцев                                   DF=1

CLUSTER 59141 | size=25
  гриб                                          DF=9
  грибів                                        DF=6
  1513 гриб                                     DF=4
  втрат гриб                                    DF=4
  гриб 310                                      DF=3
  гриб реєстр                                   DF=3
  україни гриб                                  DF=2
  137 гриб                                      DF=1
  150 гриб                                      DF=1
  17 гриб                                       DF=1
  19 гриб                                       DF=1
  30 гриб                                       DF=1
  313 гриб                                      DF=1
  525 гриб                                      DF=1
  57 гриб                                       DF=1
  58 гриб                                       DF=1
  99 гриб                                       DF=1
  водоростей грибів                             DF=1
  гриби                                         DF=1
  грибів крім                                   DF=1

CLUSTER 52677 | size=11
  змінювати запах                               DF=10
  14 запахом                                    DF=1
  запах або                                     DF=1
  запах чи                                      DF=1
  запаху та                                     DF=1
  змінювати аромат                              DF=1
  нюхання термін                                DF=1
  смаку можуть                                  DF=1
  смаку терміни                                 DF=1
  характерним запахом                           DF=1
  характерного запаху                           DF=1

In [16]:
cluster_representative = {}

for label, kws in clusters.items():
    best_kw = max(kws, key=lambda x: kw_counter[x])
    cluster_representative[label] = best_kw
kw_to_cluster = {}
kw_to_representative = {}

for label, kws in clusters.items():
    representative = cluster_representative[label]

    for kw in kws:
        kw_to_cluster[kw] = label
        kw_to_representative[kw] = representative

In [17]:
def transformer_neighbor_deduplicate_keywords(value, max_keywords=10):
    keywords = parse_keywords(value)

    result = []
    used_clusters = set()

    for kw in keywords:
        kw_norm = normalize_kw(kw)

        if not kw_norm:
            continue

        cluster_id = kw_to_cluster.get(kw_norm)

        if cluster_id is None:
            cluster_id = f"single::{kw_norm}"
            representative = kw_norm
        else:
            representative = kw_to_representative[kw_norm]

        if cluster_id in used_clusters:
            continue

        used_clusters.add(cluster_id)
        result.append(representative)

        if max_keywords is not None and len(result) >= max_keywords:
            break

    return result

In [18]:
df["keywords_keybert_transformer_dedup"] = df[KEYWORD_COL].apply(
    lambda x: transformer_neighbor_deduplicate_keywords(x, max_keywords=10)
)

df["num_keywords_transformer_dedup"] = df["keywords_keybert_transformer_dedup"].apply(len)

df[[
    "doc_id",
    KEYWORD_COL,
    "keywords_keybert_transformer_dedup",
    "num_keywords_transformer_dedup"
]].head(10)

,doc_id,keywords_keybert,keywords_keybert_transformer_dedup,num_keywords_transformer_dedup
0,12273_Порівняльна таблиця (04.12.2024),"[""бюджет україни"", ""україни 2023"", ""закон укра...",[закону україни],1
1,12272_Порівняльна таблиця (04.12.2024),"[""бюджетний кодекс"", ""україни відомості"", ""зді...",[закону україни],1
2,12274_Порівняльна таблиця (03.12.2024),"[""бюджет україни"", ""україни 2023"", ""закон укра...",[закону україни],1
3,12275_Порівняльна таблиця (04.12.2024),"[""закону україни"", ""закон україни"", ""законами ...",[закону україни],1
4,12276_Порівняльна таблиця (04.12.2024),"[""особливостей оподаткування"", ""податку стаття...",[закону україни],1
5,12271_Порівняльна таблиця (Друге читання),"[""рада україни"", ""україни постановляє"", ""украї...","[закону україни, південний машинобудівний]",2
6,12280_Порівняльна таблиця (04.12.2024),"[""караються позбавленням"", ""позбавленням волі""...",[закону україни],1
7,12282_Порівняльна таблиця (04.12.2024),"[""закону україни"", ""акта законодавства"", ""визн...",[закону україни],1
8,12281_Порівняльна таблиця (04.12.2024),"[""закону україни"", ""судочинства україни"", ""акт...",[закону україни],1
9,12280_Порівняльна таблиця (Друге читання),"[""україни верховна"", ""україни реєстраційний"", ...",[закону україни],1

In [19]:
def build_df_table(df, keyword_col, top_n=30):
    total_docs = len(df)
    counter = Counter()

    for value in df[keyword_col]:
        kw_list = value if isinstance(value, list) else parse_keywords(value)

        unique_kws = set()

        for kw in kw_list:
            kw_norm = normalize_kw(kw)
            if kw_norm:
                unique_kws.add(kw_norm)

        counter.update(unique_kws)

    result = pd.DataFrame(counter.items(), columns=["KW", "DF"])
    result["DF%"] = (result["DF"] / total_docs * 100).round(1)

    result = result.sort_values(
        ["DF", "KW"],
        ascending=[False, True]
    ).head(top_n).reset_index(drop=True)

    return result

In [20]:
print(" ДО TRANSFORMER-ДЕДУПЛІКАЦІЇ ")
print(build_df_table(df, KEYWORD_COL, top_n=30).to_string(index=False))

print("\n ПІСЛЯ TRANSFORMER-ДЕДУПЛІКАЦІЇ ")
print(build_df_table(df, "keywords_keybert_transformer_dedup", top_n=30).to_string(index=False))

 ДО TRANSFORMER-ДЕДУПЛІКАЦІЇ
                            KW   DF  DF%
                закону україни 3801 45.1
                 закон україни 2508 29.8
               законів україни 1775 21.1
               кодексу україни 1526 18.1
           порівняльна таблиця 1121 13.3
             міністрів україни  981 11.6
               законом україни  929 11.0
               бюджету україни  707  8.4
                кодекс україни  681  8.1
            україни підписувач  628  7.5
              депутати україни  616  7.3
                бюджет україни  569  6.8
                україни стаття  525  6.2
                 норми проекту  514  6.1
                 актів україни  504  6.0
                проекту закону  484  5.7
           законодавства зміст  479  5.7
                  ради україни  471  5.6
               депутат україни  451  5.4
           конституції україни  440  5.2
               республіки крим  390  4.6
              законами україни  347  4.1
                 україни закон  338  4.0
         україни реєстраційний  315  3.7
               безпеки україни  302  3.6
         законодавства україни  301  3.6
                  рада україни  292  3.5
адміністративні правопорушення  290  3.4
           деяких законодавчих  283  3.4
          конституцією україни  277  3.3

 ПІСЛЯ TRANSFORMER-ДЕДУПЛІКАЦІЇ
                                                 KW   DF  DF%
                                     закону україни 8420 99.9
                                 президента україни  277  3.3
сертифікат 58e2d9e7f900307b04000000235a2f00530f9200  184  2.2
                               процедур банкрутства  155  1.8
                             міжнародних стандартів  139  1.6
                          спричиненої коронавірусом  133  1.6
                                                ніж  117  1.4
                                            сумі не  116  1.4
                            звукозапису відеозапису   92  1.1
           58e2d9e7f900307b04000000235a2f00530f9200   85  1.0
                                      осіб біженців   75  0.9
                                            меншини   69  0.8
                                                кіт   65  0.8
                                    квот визначених   64  0.8
                                          крим міст   59  0.7
                                  україни тютюнових   59  0.7
                            репресій комуністичного   53  0.6
                                           одягу та   50  0.6
                                               гриб   47  0.6
                                     україни пенсії   46  0.5
                                      1123 железняк   43  0.5
                                    вимпели прапори   42  0.5
                                       281 салійчук   41  0.5
                            генетично модифікованих   41  0.5
                                    україни вільний   40  0.5
                               згоряння приміщеннях   39  0.5
                                 дітей інвалідністю   38  0.5
                             пестициди агрохімікати   36  0.4
                          інтелектуальної власності   35  0.4
                                    зеленим тарифом   34  0.4

In [21]:
output_path = Path("../dataset_comparative_2020_2026/comparative_files/keywords_keybert_transformer_dedup.csv")

df_to_save = df.copy()

df_to_save["keywords_keybert_transformer_dedup"] = df_to_save["keywords_keybert_transformer_dedup"].apply(
    lambda x: json.dumps(x, ensure_ascii=False)
)

df_to_save.to_csv(output_path, index=False, encoding="utf-8-sig")

print(f"Збережено → {output_path}")

Збережено → ..\dataset_comparative_2020_2026\comparative_files\keywords_keybert_transformer_dedup.csv

In [22]:
input_path = Path("../dataset_comparative_2020_2026/comparative_files/keywords_keybert_transformer_dedup.csv")

df = pd.read_csv(input_path)

KEYWORD_COL = "keywords_keybert_transformer_dedup"

print(df.columns.tolist())
print("Документів:", len(df))

['doc_id', 'length', 'rubric', 'outcome', 'num_stages', 'main_committee', 'card_id', 'reg_num', 'reg_date', 'keywords_keybert', 'num_keywords', 'keywords_keybert_transformer_dedup', 'num_keywords_transformer_dedup']
Документів: 8427

In [23]:
KEYWORD_COL = "keywords_keybert"

In [24]:
def parse_keywords(value):
    if pd.isna(value):
        return []

    if isinstance(value, list):
        return value

    try:
        return json.loads(value)
    except Exception:
        return []

In [25]:
def normalize_kw(kw):
    kw = str(kw).lower().strip()
    kw = kw.replace("ґ", "г")
    kw = re.sub(r"[^\w\sіїє']", " ", kw, flags=re.UNICODE)
    kw = re.sub(r"\s+", " ", kw).strip()
    return kw

In [26]:
NOISE_KEYWORDS = {
    "закону україни",
    "законів україни",
    "законом україни",
    "законі україни",
    "законами україни",
    "законах україни",
    "україни закон",

    "кодексу україни",
    "кодексом україни",
    "кодексі україни",
    "кодексів україни",

    "бюджету україни",
    "бюджетом україни",
    "бюджеті україни",

    "ради україни",
    "радою україни",

    "міністрів україни",
    "кабінету міністрів",
    "кабінетом міністрів",

    "депутат україни",
    "депутатів україни",
    "народний депутат",
    "народні депутати",
    "народних депутатів",

    "проект закону",
    "проєкту закону",
    "проекту закону",

    "акта законодавства",
    "акти законодавства",
    "актів україни",

    "україни стаття",
    "україни підписувач",
    "україни реєстраційний",
    "законодавства зміст",
    "законодавства україни",
    "президента україни",
}

In [27]:
def has_long_hash(kw):
    kw = str(kw).lower()

    # довгі hex-послідовності
    if re.search(r"[a-f0-9]{20,}", kw):
        return True

    # довгі цифрово-буквені токени
    if re.search(r"\b[a-z0-9]{25,}\b", kw):
        return True

    return False

In [28]:
def is_noise_kw(kw):
    kw_norm = normalize_kw(kw)

    if not kw_norm:
        return True

    if kw_norm in NOISE_KEYWORDS:
        return True

    if has_long_hash(kw_norm):
        return True

    return False

In [29]:
def filter_keywords(value, max_keywords=10):
    keywords = parse_keywords(value)

    result = []
    used = set()

    for kw in keywords:
        kw_norm = normalize_kw(kw)

        if is_noise_kw(kw_norm):
            continue

        if kw_norm in used:
            continue

        used.add(kw_norm)
        result.append(kw_norm)

        if max_keywords is not None and len(result) >= max_keywords:
            break

    return result

In [30]:
df["keywords_keybert_final_clean"] = df[KEYWORD_COL].apply(
    lambda x: filter_keywords(x, max_keywords=10)
)

df["num_keywords_final_clean"] = df["keywords_keybert_final_clean"].apply(len)

df[["doc_id", KEYWORD_COL, "keywords_keybert_final_clean", "num_keywords_final_clean"]].head(10)

,doc_id,keywords_keybert,keywords_keybert_final_clean,num_keywords_final_clean
0,12273_Порівняльна таблиця (04.12.2024),"[""бюджет україни"", ""україни 2023"", ""закон укра...","[бюджет україни, україни 2023, закон україни, ...",4
1,12272_Порівняльна таблиця (04.12.2024),"[""бюджетний кодекс"", ""україни відомості"", ""зді...","[бюджетний кодекс, україни відомості, здійснюю...",5
2,12274_Порівняльна таблиця (03.12.2024),"[""бюджет україни"", ""україни 2023"", ""закон укра...","[бюджет україни, україни 2023, закон україни]",3
3,12275_Порівняльна таблиця (04.12.2024),"[""закону україни"", ""закон україни"", ""законами ...","[закон україни, прав військовослужбовців, прот...",3
4,12276_Порівняльна таблиця (04.12.2024),"[""особливостей оподаткування"", ""податку стаття...","[особливостей оподаткування, податку стаття, к...",5
5,12271_Порівняльна таблиця (Друге читання),"[""рада україни"", ""україни постановляє"", ""украї...","[рада україни, україни постановляє, україни пи...",10
6,12280_Порівняльна таблиця (04.12.2024),"[""караються позбавленням"", ""позбавленням волі""...","[караються позбавленням, позбавленням волі, ка...",4
7,12282_Порівняльна таблиця (04.12.2024),"[""закону україни"", ""акта законодавства"", ""визн...",[визначених законом],1
8,12281_Порівняльна таблиця (04.12.2024),"[""закону україни"", ""судочинства україни"", ""акт...","[судочинства україни, юридичне значення]",2
9,12280_Порівняльна таблиця (Друге читання),"[""україни верховна"", ""україни реєстраційний"", ...","[україни верховна, україни автор, україни член...",10

In [31]:
from collections import Counter

def build_df_table(df, keyword_col, top_n=30):
    total_docs = len(df)
    counter = Counter()

    for value in df[keyword_col]:
        kw_list = value if isinstance(value, list) else parse_keywords(value)

        unique_kws = set()

        for kw in kw_list:
            kw_norm = normalize_kw(kw)
            if kw_norm:
                unique_kws.add(kw_norm)

        counter.update(unique_kws)

    result = pd.DataFrame(counter.items(), columns=["KW", "DF"])
    result["DF%"] = (result["DF"] / total_docs * 100).round(1)

    result = result.sort_values(
        ["DF", "KW"],
        ascending=[False, True]
    ).head(top_n).reset_index(drop=True)

    return result

In [32]:
print(" ПІСЛЯ ФІЛЬТРАЦІЇ ШУМУ ")
print(build_df_table(df, "keywords_keybert_final_clean", top_n=30).to_string(index=False))

 ПІСЛЯ ФІЛЬТРАЦІЇ ШУМУ
                            KW   DF  DF%
                 закон україни 2499 29.7
                кодекс україни  678  8.0
              депутати україни  607  7.2
                бюджет україни  523  6.2
           конституції україни  432  5.1
               безпеки україни  290  3.4
                  рада україни  288  3.4
          конституцією україни  266  3.2
адміністративні правопорушення  250  3.0
        законодавством україни  243  2.9
           податкового кодексу  224  2.7
           деяких законодавчих  210  2.5
            законодавчих актів  172  2.0
            бюджетного кодексу  159  1.9
                суддів україни  147  1.7
             україни відомості  144  1.7
         чинного законодавства  143  1.7
                  бюро україни  141  1.7
                 норми проекту  132  1.6
               оборони україни  132  1.6
              фінансів україни  128  1.5
                 норми чинного  125  1.5
                 банку україни  124  1.5
               республіки крим  124  1.5
               юстиції україни  122  1.4
          інвалідністю україні  119  1.4
         кримінального кодексу  116  1.4
           порівняльна таблиця  115  1.4
         правопорушення стаття  109  1.3
           страхування україни  108  1.3

In [33]:
output_path = Path("../dataset_comparative_2020_2026/comparative_files/keywords_keybert_final_clean.csv")

df_to_save = df.copy()

df_to_save["keywords_keybert_final_clean"] = df_to_save["keywords_keybert_final_clean"].apply(
    lambda x: json.dumps(x, ensure_ascii=False)
)

df_to_save.to_csv(output_path, index=False, encoding="utf-8-sig")

print(f"Збережено → {output_path}")

Збережено → ..\dataset_comparative_2020_2026\comparative_files\keywords_keybert_final_clean.csv

In [34]:
def parse_keywords(value):
    if pd.isna(value):
        return []

    if isinstance(value, list):
        return value

    try:
        return json.loads(value)
    except Exception:
        return []

In [35]:
# Перетворюємо колонку зі списками KW
kw_lists = df[KEYWORD_COL].apply(parse_keywords)

# Кількість KW у кожному документі
kw_counts = kw_lists.apply(len)

# Усі KW одним списком
all_keywords = []

for kws in kw_lists:
    for kw in kws:
        kw = str(kw).strip().lower()
        if kw:
            all_keywords.append(kw)

unique_keywords = set(all_keywords)

In [36]:
summary = pd.DataFrame({
    "Показник": [
        "Документів",
        "Середня к-сть KW",
        "Мін к-сть KW",
        "Макс к-сть KW",
        "Медіана KW",
        "Стд. відхилення KW",
        "Унікальних KW",
    ],
    "Після дедуплікації": [
        f"{len(df):,}",
        f"{kw_counts.mean():.1f}",
        f"{kw_counts.min():.0f}",
        f"{kw_counts.max():.0f}",
        f"{kw_counts.median():.1f}",
        f"{kw_counts.std():.2f}",
        f"{len(unique_keywords):,}",
    ],
})

print(summary.to_string(index=False))

          Показник Після дедуплікації
        Документів              8,427
  Середня к-сть KW               20.9
      Мін к-сть KW                  5
     Макс к-сть KW                 50
        Медіана KW               12.0
Стд. відхилення KW              18.20
     Унікальних KW             66,552

In [37]:
from pathlib import Path
import pandas as pd
import json

BASE_DIR = Path("../dataset_comparative_2020_2026")

input_csv = BASE_DIR / "comparative_files" / "keywords_keybert_final_clean.csv"
output_parquet = BASE_DIR / "comparative_files" / "keywords_keybert_final_clean.parquet"

df = pd.read_csv(input_csv)

print(df.columns.tolist())
print("Документів:", len(df))
df.head()

['doc_id', 'length', 'rubric', 'outcome', 'num_stages', 'main_committee', 'card_id', 'reg_num', 'reg_date', 'keywords_keybert', 'num_keywords', 'keywords_keybert_transformer_dedup', 'num_keywords_transformer_dedup', 'keywords_keybert_final_clean', 'num_keywords_final_clean']
Документів: 8427

,doc_id,length,rubric,outcome,num_stages,main_committee,card_id,reg_num,reg_date,keywords_keybert,num_keywords,keywords_keybert_transformer_dedup,num_keywords_transformer_dedup,keywords_keybert_final_clean,num_keywords_final_clean
0,12273_Порівняльна таблиця (04.12.2024),172,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45350,12273,2024-12-02,"[""бюджет україни"", ""україни 2023"", ""закон укра...",5.0,"[""закону україни""]",1,"[""бюджет україни"", ""україни 2023"", ""закон укра...",4
1,12272_Порівняльна таблиця (04.12.2024),376,Економічна політика,in_progress,4,Підласа Р. А. Комітет Верховної Ради України з...,45328,12272,2024-12-02,"[""бюджетний кодекс"", ""україни відомості"", ""зді...",5.0,"[""закону україни""]",1,"[""бюджетний кодекс"", ""україни відомості"", ""зді...",5
2,12274_Порівняльна таблиця (03.12.2024),145,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45349,12274,2024-12-02,"[""бюджет україни"", ""україни 2023"", ""закон укра...",5.0,"[""закону україни""]",1,"[""бюджет україни"", ""україни 2023"", ""закон укра...",3
3,12275_Порівняльна таблиця (04.12.2024),476,Безпека і оборона,in_progress,4,Завітневич О. М. Комітет Верховної Ради Україн...,45341,12275,2024-12-02,"[""закону україни"", ""закон україни"", ""законами ...",5.0,"[""закону україни""]",1,"[""закон україни"", ""прав військовослужбовців"", ...",3
4,12276_Порівняльна таблиця (04.12.2024),499,Економічна політика,in_progress,4,Гетманцев Д. О. Комітет Верховної Ради України...,45363,12276,2024-12-02,"[""особливостей оподаткування"", ""податку стаття...",5.0,"[""закону україни""]",1,"[""особливостей оподаткування"", ""податку стаття...",5

In [39]:
df_to_save = df.copy()
output_csv = Path("../dataset_comparative_2020_2026/comparative_files/keywords_keybert_final_clean.csv")
output_parquet = Path("../dataset_comparative_2020_2026/comparative_files/keywords_keybert_final_clean.parquet")


# Для CSV списки треба зберігати як JSON-рядки
df_csv = df_to_save.copy()
df_csv["keywords_keybert_final_clean"] = df_csv["keywords_keybert_final_clean"].apply(
    lambda x: json.dumps(x, ensure_ascii=False)
)

df_csv.to_csv(output_csv, index=False, encoding="utf-8-sig")

# Для Parquet можна залишити справжні списки
df_to_save.to_parquet(output_parquet, index=False)

print(f"CSV збережено → {output_csv}")
print(f"Parquet збережено → {output_parquet}")

CSV збережено → ..\dataset_comparative_2020_2026\comparative_files\keywords_keybert_final_clean.csv
Parquet збережено → ..\dataset_comparative_2020_2026\comparative_files\keywords_keybert_final_clean.parquet